version: '3.1'

services:

  app:
    build: .
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      - .env